/// Reads MAPS_API_KEY from android/local.properties and generates
/// web/maps_config.js so both Android and Web share the same key.
///
/// Usage:
///   dart run tool/generate_web_maps_config.dart
library;

import 'dart:io';

void main() {
  final localProperties = File('android/local.properties');
  if (!localProperties.existsSync()) {
    stderr.writeln(
      'Error: android/local.properties not found.\n'
      'Make sure you run this from the project root directory.',
    );
    exit(1);
  }

  final lines = localProperties.readAsLinesSync();
  String? mapsApiKey;
  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.startsWith('MAPS_API_KEY=')) {
      mapsApiKey = trimmed.substring('MAPS_API_KEY='.length).trim();
      break;
    }
  }

  if (mapsApiKey == null || mapsApiKey.isEmpty) {
    stderr.writeln(
      'Error: MAPS_API_KEY not found in android/local.properties.\n'
      'Add a line like:\n'
      '  MAPS_API_KEY=your_google_maps_api_key_here',
    );
    exit(1);
  }

  // Validate the key contains only safe characters (alphanumeric, hyphens, underscores)
  if (!RegExp(r'^[A-Za-z0-9_-]+$').hasMatch(mapsApiKey)) {
    stderr.writeln(
      'Error: MAPS_API_KEY contains invalid characters.\n'
      'Expected only alphanumeric characters, hyphens, and underscores.',
    );
    exit(1);
  }

  final output = File('web/maps_config.js');
  output.writeAsStringSync(
    '// Auto-generated by tool/generate_web_maps_config.dart\n'
    '// Do NOT commit this file (it is gitignored).\n'
    'window._touchGrassEnv = window._touchGrassEnv || {};\n'
    "window._touchGrassEnv.GOOGLE_MAPS_API_KEY = '$mapsApiKey';\n",
  );

  stdout.writeln(
    '✅ web/maps_config.js generated from android/local.properties',
  );
}
